# Generated by Django 5.2.7 on 2026-08-22 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('storage_key', models.CharField(max_length=128, unique=True)),
                ('content_type', models.CharField(max_length=64)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='images_imag_owner_i_05fc84_idx'), models.Index(fields=['owner', 'name'], name='images_imag_owner_i_2b6462_idx')],
            },
        ),
    ]
