# Generated by Django 5.2.7 on 2026-08-20 18:08

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='Asia/Tashkent', help_text='Used for all schedule and reminder calculations.'),
        ),
    ]
