# Generated by Django 5.2.7 on 2026-08-20 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('vault_item.created', 'Vault item created'), ('vault_item.updated', 'Vault item updated'), ('vault_item.deleted', 'Vault item deleted'), ('vault.revealed', 'Vault secret revealed'), ('vault.reveal_failed', 'Vault reveal failed'), ('vault.file.uploaded', 'Vault file uploaded'), ('vault.file.downloaded', 'Vault file downloaded'), ('vault.file.deleted', 'Vault file deleted'), ('bulldrop.claimed', 'BullDrop reward claimed'), ('bulldrop.claim_rejected', 'BullDrop claim rejected'), ('auth.login', 'Login'), ('auth.login_failed', 'Login failed'), ('auth.logout', 'Logout'), ('auth.register', 'Registration'), ('permission.granted', 'Permission granted'), ('permission.revoked', 'Permission revoked'), ('user.activated', 'User activated'), ('user.deactivated', 'User deactivated')], db_index=True, max_length=64)),
                ('resource_type', models.CharField(blank=True, default='', max_length=32)),
                ('resource_id', models.CharField(blank=True, default='', max_length=64)),
                ('outcome', models.CharField(choices=[('success', 'success'), ('failure', 'failure')], default='success', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', 'action', '-created_at'], name='core_auditl_actor_i_197bda_idx'), models.Index(fields=['resource_type', 'resource_id'], name='core_auditl_resourc_a674ad_idx')],
            },
        ),
    ]
