# Generated by Django 5.2.7 on 2026-08-20 13:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BullDropAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('username', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulldrop_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BullDropClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('promo_code', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='bulldrop.bulldropaccount')),
            ],
            options={
                'ordering': ['-claimed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bulldropaccount',
            index=models.Index(fields=['user'], name='bulldrop_bu_user_id_f36cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='bulldropclaim',
            index=models.Index(fields=['account', '-claimed_at'], name='bulldrop_bu_account_226bb9_idx'),
        ),
    ]
