# Generated by Django 5.2.7 on 2026-08-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulldrop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulldropclaim',
            name='note',
        ),
        migrations.RemoveField(
            model_name='bulldropclaim',
            name='promo_code',
        ),
        migrations.AddField(
            model_name='bulldropaccount',
            name='browser',
            field=models.CharField(choices=[('chrome', 'Google Chrome'), ('opera', 'Opera'), ('duckduckgo', 'DuckDuckGo'), ('edge', 'Microsoft Edge'), ('firefox', 'Firefox'), ('brave', 'Brave'), ('other', 'Other')], default='chrome', max_length=20),
        ),
    ]
